### ISSUE TITLE
dataset official website

### ISSUE THREAD

**Issue by wangjianan-123** [truong11062002/yolov8_for_human_detection#1]
Hello, thank you for providing the YOLOv8s model. I am curious about the source of the human_detection_dataset dataset, can you tell me where the dataset official website is?

**Comment by SuperbTUM** [comment]
Looks like a custom dataset with continuous frames from a bunch of short video sequences recorded by a single imou camera.

**Comment by truong11062002** [comment]
> Looks like a custom dataset with continuous frames from a bunch of short video sequences recorded by a single imou camera.

That's so true. This dataset has no official website.

**Comment by wangjianan-123** [comment]
ok,thank you for answers
